CPLUSPLUS      = g++ # C++ compiler
CPLUSPLUS_MPI  = mpicxx # intel mpi or mpich
FORTRAN        = gfortran # Fortran compiler
BOOST_DIR      = /usr/local
LAPACK_DIR     = /usr/local
FFTW_DIR       = /usr/local
ELPA_DIR       = /usr/local
SCALAPACK_DIR  = /usr/local
CEREAL_DIR     = /usr/local

OBJ_DIR = obj
NP      = 14
